### ISSUE TITLE
[Campinas-SP] Desenvolvedor PHP - Presencial

### ISSUE THREAD

**Issue by thiagodionizio** [PHPcomRapadura/Vagas#12]
Olá amigos, temos uma vaga aberta para Desenvolvedor PHP - Presencial, para um cliente nosso em Campinas/SP

Interessados, falar comigo no whatsapp(85) 981152855

**Comment by alessandrofeitoza** [comment]
Vou fechar a issue pq já faz um bom tempo que está aberta. Se a vaga ainda tiver aberta é melhor criar uma nova issue.
