### ISSUE TITLE
[REMOTO] Desenvolvedor Fullstack (Node.js / MongoDB e PHP / MySQL)

### ISSUE THREAD

**Issue by ital0** [PHPcomRapadura/Vagas#13]
LINK DA VAGA: [https://nextar.enlizt.me/vagas/desenvolvedor_fullstack_(node.js_+-+_mongodb_e_php_+-+_mysql)-150218](https://nextar.enlizt.me/vagas/desenvolvedor_fullstack_(node.js_+-+_mongodb_e_php_+-+_mysql)-150218)

A **NEXTAR** acredita nas pessoas e no empreendedorismo. Por isso, trabalhamos intensamente para desenvolver e entregar software simples e de qualidade para mais de 46 mil pequenos comerciantes no Brasil e no mundo.

A Simplicidade de uso do nosso software é a proposta de valor mais valorizada pelos nossos clientes. Resolver problemas complexos com telas e processos simples tem sido o nosso diferencial há mais de 15 anos no mercado. A usabilidade, um atendimento Incrível juntamente com um modelo de distribuição inovador é o que tem feito nossa base de clientes crescer em ritmo acelerado todos os dias.

Estamos em busca de um Desenvolvedor Full Stack para nos ajudar na expansão da nossa plataforma de gestão de contas e sistemas internos. Precisa ser totalmente apaixonado por tecnologia e pessoas. Gostar de aprender, abraçar desafios e acima de tudo, adorar trabalhar em equipe. Temos um sonho grande. Nosso objetivo é ser a principal plataforma de gestão comercial para o pequeno e médio lojista. E para isso precisamos de mais um super talento.

**Como você poderá ajudar:**
Mantendo e desenvolvendo novas features de nossas APIs de contas, produtos e sistemas internos, além de ajustar e implementar novas integrações backend com serviços de terceiros e nossos próprios produtos.

**Procuramos alguém:**

- Com experiência e conhecimento avançados nas dobradinhas Node.js e MongoDB e PHP e MySQL.
- Serão diferenciais conhecimentos em Ruby e Python e algum front-end framewok como React ou Vue.JS
- Com bons conhecimentos de arquitetura de sistemas, conceitos de microserviços e familiaridade com ecossistema da AWS.
- Com conhecimento em padrões de desenvolvimento de software e suíte de testes (funcionais, unitários, de integridade, de integração e de performance);
- Que consiga atuar tanto no Front-End quanto no Back-End;
- Criatividade para achar soluções simples para problemas complexos.
- Humildade para receber com entusiasmo insights construtivos sobre o seu trabalho e disposição para buscar novos caminhos quando necessário.
- Perfeccionismo e muita vontade de achar a melhor solução para um problema real dos nossos clientes.
- Atitude positiva em relação ao seu trabalho e a todas as pessoas ao seu redor.

**Local de trabalho:**
Temos flexibilidade. Você trabalhará diretamente com um desenvolvedor localizado em São Paulo, trabalhando remotamente de casa, cafés e co-working. O escritório da empresa, com a maior parte dos colaboradores está em Florianópolis, em um ambiente incrível junto as melhores empresas de tecnologia de Santa Catarina. Mas se você for o candidato perfeito para esta vaga e também for incrivelmente produtivo trabalhando remoto, você poderá trabalhar de qualquer lugar do mundo.

**O que nós oferecemos:**
Contratação CLT;
Plano de Saúde (após 3 meses);
Vale-Refeição ou Alimentação: R$ 600,00;
Vale Transporte (ou estacionamento gratuito);
Vale Bem-Estar (auxílio academia);
Auxílio financeiro para cursos, treinamentos e eventos (analisado caso a caso);
Liberdade de horário;
E se você trabalhar em nosso escritório em Florianópolis, você poderá usufruir também de:

No dress code;
Café espresso à vontade;
Café da manhã e lanches saudáveis à vontade;
HappyNEX: 1 vez por mês a empresa ajuda na cerveja (ou no suco!);
Ótimo ambiente de trabalho (empresa vencedora do prêmio “No Caminho Certo” de 2016 da Virtvs e Great Place to Work).

**Comment by alissonsilvas** [comment]
@ital0 Vaga tá topper!
