### ISSUE TITLE
[Fortaleza] - Desenvolvedor Web (PHP + JQuery)

### ISSUE THREAD

**Issue by IuryChristmas** [PHPcomRapadura/Vagas#15]
# Inhaêh

Estamos procurando por desenvolvedores desenrolados, com sangue nos zói e sede de conhecimento.

Requisitos:
Ter conhecimento em PHP/OO e Javascript e JQuery
Que se dê bem com nosso amiguinho Linux
Saiba utilizar Git, mas senão souber, é fácim mah... Nós te ensinamos
Ser auto-gerenciável
Que não tenha frescura em aprender e ensinar
Experiência mínima de 6 meses(mas senão estiver experiência nenhuma, mas for desenrolado e tiver um github daora, manda aê pra darmos uma olhada)

Observações:
A vaga não é remoto
Inicialmente não será carteira assinada, mas existe a possibilidade de assinar a carteira
Passagem + Vale Transporte
Salário é negociável
Horário de Seg-Sex de 9h às 18h

mandar CV com pretensão salarial pra: iury.christmas@gmail.com

**Comment by JoaoAF** [comment]
Onde é a empresa ? Qual o endereço ?

**Comment by IuryChristmas** [comment]
Estamos nos mudando pra Av. Santos Dumont, Aldeota
Antes ficávamos na Maraponga

**Comment by erandirjunior** [comment]
Qual a empresa por gentileza?
