### ISSUE TITLE
(Munique e Munster) PHP com Symfony Senior 

### ISSUE THREAD

**Issue by gchaves04** [PHPcomRapadura/Vagas#16]
Tenho 8 oportunidades para recolocação para a Alemanha, para um projeto global em inglês. 
Esse desenvolvedor tem mais de 5 anos de experiência, conhecimentos em Symfony e inglês avançado.
Interessados mandar CV atualizado em inglês para Gabriel@zerotoonesearch.com.

**Comment by alessandrofeitoza** [comment]
Vou fechar a issue pq já faz um bom tempo que está aberta. Se a vaga ainda tiver aberta é melhor criar uma nova issue.
