### ISSUE TITLE
[Aquiraz] Senior  Developer PHP/Symfony2

### ISSUE THREAD

**Issue by alefcastelo** [PHPcomRapadura/Vagas#2]
![company-logo](https://user-images.githubusercontent.com/4504483/27800256-efd42994-5fee-11e7-8530-366ff9cac7a8.png)

Olá pessoal! Em PetCoach estamos procurando um senior developer em Symfony2 para nossa equipe.

**Skills necessárias:**

- Amplo conhecimento de Symfony2 e PHP
- HTML5, JS, CSS3
- Design patterns.
- Experiência em produtos mobile.
- Ampla experiencia em RESTFull APIs.
- Experiência com autenticação OAuth.2.0
- Inglês básico

Skills extra:
- Conhecimentos de administração de servidores (AWS)
- Conhecimentos de Node.js
- Backbone, require.js, Phonegap.
- Espanhol

**Vantagens de trabalhar com a gente:**

- Trabalhar em um projeto internacional.
- Trabalhar para uma empresa consolidada nos EUA.
- Ambiente descontraido.
- Certificações pagas pela empresa.

Localizacão: Spartan Headquarters: https://goo.gl/maps/3ZgajdwAdQS2

Enviar currículo para: **career@petcoach.co**

**Mais info sobre a empresa:**

http://www.petcoach.co/
http://www.philly.com/philly/business/small_business/Philly-start-up-PetCoach-sold-to-Petco.html
https://about.petco.com/2017-04-04-Petco-acquires-leading-pet-advice-website-and-app-PetCoach
http://www.philly.com/philly/business/small_business/Philly-start-up-PetCoach-sold-to-Petco.html
http://technical.ly/philly/2014/08/13/petcoach-pet360-investment/
http://articles.philly.com/2014-07-11/news/51361047_1_pet-owners-pet-parents-pet-health
http://www.brit.co/apps-for-busy-pet-parents/

**Comment by alissonsilvas** [comment]
@alefcastelo 👏🏽👏🏽👏🏽👏🏽

**Comment by dersonsena** [comment]
@AlissonSilvaCe Massa essa vaga! Vou ver se passo para um amigo

**Comment by rtio** [comment]
@AlissonSilvaCe Aí sim viu!

**Comment by alefcastelo** [comment]
Vaga ainda aberta!

**Comment by ianrodrigues** [comment]
@alefcastelo vou tentar também, acredito que me qualifico pra vaga :D

**Comment by alefcastelo** [comment]
@iansrodrigs acredito também, que você se qualifica pra essa vaga!

**Comment by ianrodrigues** [comment]
Valeu, enviado!

**Comment by alessandrofeitoza** [comment]
Vou fechar a issue pq já faz um bom tempo que está aberta. Se a vaga ainda tiver aberta é melhor criar uma nova issue.
