### ISSUE TITLE
[Joinville/SC] PHP Developer Pleno na RotaExata

### ISSUE THREAD

**Issue by Vagas-HunterCo** [PHPcomRapadura/Vagas#24]
**Descrição da vaga**
Venha participar do desenvolvimento da nova versão do nosso sistema.

**Local:** Escritório, Joinville/SC

**Benefícios**
Um ambiente de trabalho flexível, com grandes possibilidades de crescimento
Auxilio alimentação
Oportunidade de eventos e cursos que vão turbinar seus conhecimentos
Auxilio transporte
Ótimo ambiente de trabalho

**Requisitos Obrigatórios**
Conhecimento com desenvolvimento em PHP
Experiência com ambientes AWS (Amazon), Nodejs, Express, Serverless, Mongodb, Mysql ou Postgres
Boa capacidade de análise de ambientes WEB Servless
Conhecer o GIT (ferramenta de controle de versões)
Formação desejada: Graduação nas áreas de desenvolvimento de sistemas ou áreas afins.
Residir em Joinville/SC 

**Diferenciais**
Vue
Docker

**Contratação:** CLT -R$ 3.500,00 - R$ 4.000,00

**Nossa empresa**
Fundada em Maio de 2011 em Joinville/SC, a RotaExata tornou-se pioneira em desenvolvimento de sistemas inovadores para a área de gestão de frotas. Não medimos esforços para manter uma cultura livre e inovadora onde todos os colaboradores são participativos e sentem-se confortáveis para trocar ideias e opiniões.

Buscamos pessoas com boa capacidade de aprendizado, autodidatas, com facilidade em resolver
problemas, que tenha pensamento lógico, saiba trabalhar em equipe e tenha boa comunicação.

**Como se candidatar**
[Clique aqui](https://vagas.hunterco.com.br/job/5c8a9474aef434000f12b9b6)

**Labels** 

**Alocação:** Presencial em Joinville-SC
**Contratação:** CLT
**Experiência:** Pleno

**Comment by alessandrofeitoza** [comment]
Vou fechar a issue pq já faz um bom tempo que está aberta. Se a vaga ainda tiver aberta é melhor criar uma nova issue.
