### ISSUE TITLE
[Campinas/SP] PHP Developer na Kikker

### ISSUE THREAD

**Issue by thiagodionizio** [PHPcomRapadura/Vagas#25]
## Descrição da vaga
Este profissional irá desenvolver ferramentas que auxiliem a gestão da empresa, assim como mudar alguns processos de nossos clientes.
Hoje a Kikker é uma empresa situada em Campinas - SP. Onde faz parte de um Hub de Tecnologia situado no Castelo.
Temos feitos coisas desafiadoras, trabalhando com ciência de dados, construção de painéis, que facilitam a vida do nosso cliente e equipe.

## Local

Escriório Campinas/SP  - Castelo

## Benefícios

- Plano de saúde

#### Diferenciais

- Horários flexíveis, 
- No Dress Code.

## Requisitos

**Obrigatórios:**
- 1 anos de experiência com PHP 5+
- 1 anos de experiência com MYSQL OU Postgresql

**Desejáveis:**
- conhecimentos em Laravel

## Contratação

PJ a combinar

## Nossa empresa
Somos a Kikker, especialista em software de gestão de cadeia e estoque e que utiliza um software para o varejo que ajuda a eliminar as rupturas, quebras e excesso do estoque.

## Como se candidatar

Por favor envie um email para thiago.dionizio@kikker.com.br com seu CV anexado - enviar no assunto: Vaga PHP - Campinas

### Alocação:
- Presencial
- Flexível (Remoto parcial)

### Contratação:
- PJ
- Freelance
- Estágio

### Experiência
- Estágio
- Júnior
- Pleno

**Comment by alessandrofeitoza** [comment]
Vou fechar a issue pq já faz um bom tempo que está aberta. Se a vaga ainda tiver aberta é melhor criar uma nova issue.
