### ISSUE TITLE
[Fortaleza/Remoto] - Dev ReactJs Pleno/Senior

### ISSUE THREAD

**Issue by alessandrofeitoza** [PHPcomRapadura/Vagas#27]
# Vaga: Dev ReactJS Pleno/Senior Remoto

E aew minha jóia, estamos procurando você, desenvolvedora(or), que gosta de desafios, que manja dos paranauê, você que consegue fazer um incêndio esfregando duas pedras de gelo, você que é tão foda a ponto de ter nascido antes mesmo de seus pais, você que toda manhã acorda seu próprio despertador.

Somos uma fábrica de software com alguns projetos muito bons utilizando boas tecnologias e boas maneiras de produzir código.

Se você acha que dá pro gasto então se apruma e venha fazer parte dessa equipe rocheda.

## Algumas características sobre o job:
    - Contratação PJ (Sálario entre R$ 4 e R$ 6k por mês, dependendo da experiência e do teste prático);
    - Remoto;
    - 40 horas semanais, horário comercial, podemos flexibilizar um pouco;
    - Reuniões diárias (se residir no Ceará podem ser presenciais as vezes)
    - Período mínimo do projeto: 03 meses;
    
## A gente quer alguém marrom meno assim:
    - Experiência com HTML5, CSS3, SASS, Bootstrap;
    - Experiência principalmente com Javascript, JQuery e ReactJs;
    - Experiência com Git, consumo de APIs REST e trabalho em equipe;

## Diferenciais que farão a diferença:
    - React Native
    - PHP
    - Testes Automatizados;
    - Boas noções de UI/UX;
    - SOLID, Clean Code, Object Calisthenics;
    - Inglês

**Ficou interessado?**
Pois pronto, envie um e-mail para alessandrofeitoza01@gmail com as informações abaixo:

    Nome completo
    telefone para contato
    username do gitthub
    linkedin
    Curriculo em PDF

Lembre-se de mandar no assunto **[VAGA] - Dev ReactJS**

**Comment by ffcgomes** [comment]
Enviei meus dados neste momento, Alessandro.

**Comment by dersonsena** [comment]
Enviado =)

**Comment by mocraveirodev** [comment]
Acabei de te enviar.... Vi a vaga no post que a Gedeane compartilhou :D Obrigada!
