### ISSUE TITLE
[Fortaleza] VAGA PARA PROGRAMADOR PLENO

### ISSUE THREAD

**Issue by Fabinfo** [PHPcomRapadura/Vagas#3]
Pre requisitos:
Praticas em programação
Conhecimento intermediário/avançado em PHP
Disponibilidade para horário comercial.
Residir em Fortaleza-CE

Benefícios:
Vale refeição
Vale transporte
Plano de saúde apos 3 meses
Salario a combinar

Enviar curriculos para: recrutamento@fabricainfo.com

**Comment by alefcastelo** [comment]
@Fabinfo  Se possível descrever com empresa, e-mail pra contato, faixa salarial, local de trabalho e o que mais você achar interessante!

**Comment by Fabinfo** [comment]
Corrigido!

**Comment by ital0** [comment]
@Fabinfo esta vaga já foi preenchida? Em caso positivo, por favor, fecha a issue. :)

**Comment by Fabinfo** [comment]
Boa tarde.

 

Não. Estamos com ela aberta ainda, recebemos pouquíssimos currículos.

 

 

De: Ítalo Menezes [mailto:notifications@github.com] 
Enviada em: terça-feira, 6 de março de 2018 14:52
Para: PHPcomRapadura/Vagas
Cc: Fabinfo; Mention
Assunto: Re: [PHPcomRapadura/Vagas] [Fortaleza] VAGA PARA PROGRAMADOR PLENO (#3)

 

@Fabinfo <https://github.com/fabinfo>  esta vaga já foi preenchida? Em caso positivo, por favor, fecha a issue. :)
