### ISSUE TITLE
[REMOTO] Desenvolvedor PHP

### ISSUE THREAD

**Issue by IuryChristmas** [PHPcomRapadura/Vagas#30]
Vagas para Programador PHP 
Ter conhecimento em Jquey, Ajax, Mysql,  webservice, xml, PHP OO padrão MVC,  html5, bootstrap. 
Carga horária de 8 horas em home office. Salário à combinar.

Ter experiência na area será um diferencial

Empresa: Janus Educare
Interessados, entrar em contato através do telefone/whatsapp:
(61) 99308-1255 falar com Clemilson Marques

**Comment by wribeiiro** [comment]
isso esta disponivel?

**Comment by alessandrofeitoza** [comment]
Vou fechar a issue pq já faz um bom tempo que está aberta. Se a vaga ainda tiver aberta é melhor criar uma nova issue.
