### ISSUE TITLE
[Fortaleza] Desenvolvedor PHP

### ISSUE THREAD

**Issue by ghost** [PHPcomRapadura/Vagas#33]
## Descrição da empresa
- Somos uma empresa que desenvolve tecnologias, através de processamento de dados, para promover a eficiência operacional e administrativa na gestão de empresas de transporte e logística.

## Atividades e Responsabilidades
- Desenvolvimento e manutenção de sistemas.

## Requisitos
- Conhecimento em PHP, Laravel Framework 1, MySQL, Javascript, Vuejs, Jquery, HTML5, CSS, consumo e desenvolvimento de Api.

## O que nós oferecemos
 - Auxílio Transporte
 - Auxílio Refeição

## Contato

- Ricardo: +55 85 9629-7500
- E-mail: ricardo.palacio@mobs2.com

**Comment by alessandrofeitoza** [comment]
Vou fechar a issue pq já faz um bom tempo que está aberta. Se a vaga ainda tiver aberta é melhor criar uma nova issue.
