### ISSUE TITLE
[Fortaleza-CE/Remoto] - Dev PHP / WordPress

### ISSUE THREAD

**Issue by alessandrofeitoza** [PHPcomRapadura/Vagas#34]
# Vaga: Dev PHP/WP Remoto

E aew minha jóia, estamos procurando você, desenvolvedora(or) PHP, que entende um pouco das entranhas do WordPress, que domina aquele PHPzão ali por trás dos templates. Você que nunca morreu e nem tem inveja de quem morre, você que já reuniu as esferas do dragão mas quem fez o pedido foi o Shenlong, você que todas as manhãs acorda o próprio despertador.

Somos uma fábrica de software com alguns projetos internacionais muito bons utilizando boas tecnologias e boas maneiras de produzir código.

Se você acha que dá pro gasto então se apruma e venha fazer parte dessa equipe rocheda.

## Algumas características sobre o job:
    - Contratação PJ (Sálario entre R$ 3k e R$ 5k por mês, dependendo da experiência e do teste prático);
    - Totalmente Remoto;
    - 40 horas semanais, horário comercial, podemos flexibilizar um pouco;
    - Reuniões diárias (remotamente);
    
## A gente quer alguém marrom meno assim:
    - Experiência usando HTML, CSS, Bootstrap
    - Experiência com PHP;
    - Experiência com GIT;
    - Experiência com o básico do FrontEnd (transformar o design em código)

## Diferenciais que farão a diferença:
    - Experiência com Wordpress (Customização de Templates);
    - Symfony
    - React
    - Boas noções de UI/UX;
    - Inglês

**Ficou interessado?**
Pois pronto, envie um e-mail para alessandrofeitoza01@gmail.com com as informações abaixo:

    Nome completo
    telefone para contato
    username do gitthub
    linkedin
    Curriculo em PDF

Lembre-se de mandar no assunto **[VAGA] - Dev PHP**

**Comment by eerison** [comment]
Hey Menino usa o [myprofile](https://www.myprofile.pro), para gerar esse curriculo em PDF bolado :man_technologist: [:cat:](https://github.com/eerison/myprofile) 

Alguma sugestão, critica ou contribuiçao? da uma olhada nas [issues](https://github.com/eerison/myprofile/issues), o projeto e open source :heart:
