### ISSUE TITLE
[FORTALEZA/REMOTO] Fullstack Laravel + (Vue ou React-native)

### ISSUE THREAD

**Issue by victorsilent** [PHPcomRapadura/Vagas#35]
Somos a TurnoverBnB, uma SaaS Startup em crescimento rápido que provê as ferramentas necessárias para que anfitriões de alugueis por temporada possam administrar a limpeza e o agendamento de suas propriedades. TurnoverBnB é uma forma inteligente de agendar, pagar e encontrar diaristas e demais serviços de limpeza por temporada.

Estamos buscando por desenvolvedores Fullstack que contemplem as seguintes especificações:Especificações da vaga:

Salário: US$ 10/h (R$6500 ~ R$8000/mês)
Horas requeridas: 30h-40h/semanais
Remoto - Home Office
**Inglês obrigatório - Você precisará estar apto a se comunicar com o time.**

**1 - O que esperamos de você no dia a dia?**
   * Desenvolvimento de features de forma autônoma (front e back)
   * Implantação de melhorias dentro do código atual
   * Criação de testes para frontend e/ou backend
   * Compreender bem o código ja existente (Laravel 7>=, VueJS 2 + Vuetify, React-native)

**2 - Outros conhecimentos que ajudarão durante a seleção:**
   * Compreenção dos framework alem da pura utilização
   * Utilizar/ter utilizado storybook para documentação de componentes

**3 - Como aplicar:**
 * Email para joao@turnoverbnb.com com assunto [DEV FULLSTACK]

**Comment by alessandrofeitoza** [comment]
Vou fechar a issue pq já faz um bom tempo que está criada. Se a vaga ainda tiver aberta é melhor criar uma nova issue.
