### ISSUE TITLE
[Fortaleza] Desenvolvedor PHP

### ISSUE THREAD

**Issue by alissonsilvas** [PHPcomRapadura/Vagas#4]
![logo-bannet-vertical 4x-280x221](https://user-images.githubusercontent.com/5832077/28537277-abac0960-7080-11e7-8c62-fdaa5209a883.png)

**Descrição da Vaga**

Bannet seleciona Desenvolvedor PHP para o seu time:

Requisitos Obrigatórios (mínimo de 1 ano):

– PHP;
– Zend Framework 2;
– GIT;
– MySQL;
– Javascript;

Desejáveis:

– Elastic Search;
– APIgility;
– MicroServiços;
– Notificações;
– WordPress;

Local de Trabalho: Centro, Fortaleza, Ceará.
Jornada: Período Integral (manhã e tarde).

Salário Bruto: De R$ 2000,00 a R$ 3000,00

+ Vale Transporte
+ Vale Alimentação ou Refeição
+ Plano de Saúde (50%)
+ Plano Odontológico (50%)

Acesse esse link https://jobs.kenoby.com/bannet/job/desenvolvimento-php/596e142944d32076ee2c8638 e clique no botão enviar seu currículo e depois siga os passos.

Fonte: http://queroworkar.com.br/blog/job/desenvolvedor-php-17/

**Comment by alessandrofeitoza** [comment]
Vou fechar a issue pq já faz um bom tempo que está aberta. Se a vaga ainda tiver aberta é melhor criar uma nova issue.
