### ISSUE TITLE
[Remoto] Desenvolvedor Full Stack Senior

### ISSUE THREAD

**Issue by brunorbarroso** [PHPcomRapadura/Vagas#40]
Somos a Fretx, uma startup portuguesa de marketplace de transportes de mercadorias. Nossa startup é relativamente nova porém vem obtendo um crescimento rápido em pouco tempo.

Estamos buscando por um desenvolvedor fullstack que contemplem as seguintes especificações:

(se tiver conhecimento de ux/ui, será um diferencial)

**Especificações da vaga:**
Salário: R$8000 ~ R$12000/mês
Horas requeridas: 40h/semanais
Remoto - Full time - Home Office
Contrato: PJ
Não obrigatório Inglês

**Local**
A vaga é full remoto. A empresa está localizada em Lisboa, Portugal.

Horário
date_default_timezone_set('Europe/Lisbon');

**O que esperamos de você no dia a dia?**
* Desenvolvimento de features de forma autônoma (front e back)
* Implantação de melhorias dentro do código atual
* Criação de testes para frontend e/ou backend
* Compreender bem o código ja existente (Laravel 7>=, Angular e NodeJS)

**Como se candidatar**
Enviar email com CV para contact@fretx.app com assunto: Vaga Desenvolvedor Full Stack

**Comment by andersao** [comment]
Boa @brunorbarroso!

**Comment by klinsmannlopes** [comment]
Orgulho do mestre Jedi
