### ISSUE TITLE
[REMOTO][PLENO] Dev PHP

### ISSUE THREAD

**Issue by alessandrofeitoza** [PHPcomRapadura/Vagas#42]
# Vaga: Dev PHP Remoto

E aew minha jóia, estamos procurando você, desenvolvedora(or) PHP, que entende de PHP mesmo, com e sem framework, que domina aquele PHPzão ali com e sem Orientação a Objetos. Você que nunca morreu e nem tem inveja de quem morre, você que já reuniu as esferas do dragão mas quem fez o pedido foi o Shenlong, você que todas as manhãs acorda o próprio despertador.

Somos uma fábrica de software com alguns projetos internacionais muito bons utilizando boas tecnologias e boas maneiras de produzir código.

Se você acha que dá pro gasto então se apruma e venha fazer parte dessa equipe rocheda.

## Algumas características sobre o job:
    - Contratação PJ (Sálario entre R$ 4.5k e R$ 6k por mês, dependendo da experiência e do teste prático);
    - Totalmente Remoto (mesmo depois da pandemia);
    - 40 horas semanais, horário comercial, podemos flexibilizar um pouco;
    - Reuniões diárias (remotamente);
    - Comunicação quase que exclusiva pelo Discord.
    - Organização das tarefas através de Issues, Milestones e Merge Requests do Gitlab;
    
## A gente quer alguém marrom meno assim:
    - Experiência usando HTML, CSS, Bootstrap
    - Experiência e dominio da PHP (estruturado e orientado a objetos);
    - Experiência com GIT;
    - Experiência com o básico do FrontEnd (transformar o design em código, HTML, Bootstrap, JS)
    - Autodidata e que tenha sangue nos olhos pra resolver problemas (procurando, estudando, tentando, orando, chorando e etc)

## Atividades a exercer na empresa:
    - Criar novas funcionalidades em um portal, utilizando plugins bem escritos, composer, componentes do Symfony, PSR-12;
    - Dar manutenção em códigos já existentes, sempre prezando por uma qualidade no código e no fluxo das informações;
    - Criar e dar manutenção em CRUDs e Plugins;
    - Revisar códigos
    - Refatorar códigos     

## Diferenciais que farão a diferença:
    - Symfony
    - WordPress
    - Boas noções de UI/UX;
    - Inglês

## Kit boas vindas
    - 1 ano de Alura Plus, pra vocë alcançar o proximo nivel de profissionalismo 
    - Camiseta
    - Caneca para café
    - Outros itens

**Ficou interessado?**
Pois pronto, envie um e-mail para alessandrofeitoza01@gmail.com com as informações abaixo:

    Nome completo
    telefone para contato
    username do gitthub
    linkedin
    Curriculo em PDF

Lembre-se de mandar no assunto **[VAGA] - Dev PHP 2021.2 **

**Comment by chags** [comment]
Vamos lá professor!!!
