### ISSUE TITLE
[Fortaleza] Desenvolvedor PHP

### ISSUE THREAD

**Issue by vidalvasconcelos** [PHPcomRapadura/Vagas#6]
# Desenvolvedor PHP

Estamos procurando você, desenvolvedora(or), Nerd, Web Artisan, nascida(o) na tormenta, 
primeira(o) de seu nome, independente da casa que carregue em seu escudo. 

Vamos trabalhar juntos no desenvolvimento de novos projetos, aplicações legados, UX e sempre 
de forma autonoma, auto-critica e com foco nos resultados. Somos uma empresa moderna com uma 
estrutura bastante horizontal assentada no bom relacionamento da equipe, o que nos proporciona 
horários bem flexíveis e um ambiente descontraído e divertido.

Se você ama sujar as mãos com código, é viciada(o) em tecnologia e tem sangue nos olhos, esta é 
a oportunidade de trabalhar na [Pilps](http://pilps.com.br), a primeira Venture Builder do Ceará.

Veja se você tem o perfil da pessoa que procuramos.

Desafios a serem enfrentados
 - Entender de html5 e css3
 - Lidar bem com Linux, Apache e AWS.
 - Ter dominio sobre estrutura de dados, OO.
 - Conhecimento em Sass ou outros pré-processadores de CSS
 - Ter bom conhecimento sobre algum framework MVC como Laravel, CakePHP ou CodeIgniter
 - Já ter trabalhado com JQuery, ECMAscript6 e superiores
 - Ter experiência com PostgreSQL e MariaDB
 - Não fazer push direto na Master
 - Utilizar Vagrant ou Docker
 - Ser auto-gerenciável

Envie um e-mail para vagas@pilps.com.br com as informçoes a baixo:
- Nome completo
- telefone para contato
- username do gitthub
- linkedin

**Comment by vctt94** [comment]
remoto?

**Comment by walberjefferson** [comment]
Remoto?

**Comment by wilcorrea** [comment]
Se não fosse pelo "Não fazer push direto na Master" eu tava dentro :sob:

**Comment by clmadrazo** [comment]
Enviado!

**Comment by andersao** [comment]
Opa, email enviado!
