### ISSUE TITLE
[FORTALEZA] ESTAGIÁRIO DE DESENVOLVIMENTO PHP(LARAVEL)

### ISSUE THREAD

**Issue by eduardoroseo** [PHPcomRapadura/Vagas#9]
Saudações, me chamo Eduardo Roseo, trabalho atualmente na AGBSites, em breve AGBTec, estamos selecionando estagiários com conhecimentos em Laravel, ter conhecimentos sólidos nele será um diferencial. Além do Laravel, buscamos pessoas quem tenham esses conhecimentos e qualidades:

- JQuery
- HTML
- Bootstrap
- MySQL
- Saber trabalhar em equipe
- Responsabilidade

Oferecemos:
- Bolsa + meia passagem
- Oportunidade de crescimento
- Trabalhar com novas tecnologias
- Trabalhar com cryptomoedas

Interessados enviar currículo para mim diretamente: eduardoroseo@gmail.com | Telegram: 85 98817-9596
ou para o gmail da empresa: agbsites@gmail.com
Se tiver algum projeto em laravel publicado em seu github ajudará na seleção.

Boa Sorte!!

**Comment by eduardoroseo** [comment]
Contratação imediata!! Literalmente, precisamos pra ontem rs

**Comment by alissonsilvas** [comment]
@eduardoroseo kkkkkk nossa
